// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Udemy
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Course : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"Course\",\"namespace\":\"Udemy\",\"fields\":[{\"name\":\"Id\",\"doc\"" +
				":\"Course ID in Udemy\'s DB\",\"type\":\"long\"},{\"name\":\"Title\",\"type\":\"string\"},{\"nam" +
				"e\":\"Url\",\"type\":\"string\"}]}");
		/// <summary>
		/// Course ID in Udemy's DB
		/// </summary>
		private long _Id;
		private string _Title;
		private string _Url;
		public virtual Schema Schema
		{
			get
			{
				return Course._SCHEMA;
			}
		}
		/// <summary>
		/// Course ID in Udemy's DB
		/// </summary>
		public long Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				this._Title = value;
			}
		}
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				this._Url = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Title;
			case 2: return this.Url;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Int64)fieldValue; break;
			case 1: this.Title = (System.String)fieldValue; break;
			case 2: this.Url = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
